/**
 * Ed25519 public key used to verify the desktop app update manifest
 * (app/v1/<channel>/index.json on downloads.nebulis.app).
 *
 * The matching private key lives in the APP_RELEASE_SIGNING_KEY CI secret
 * (base64-encoded PKCS8 PEM). This public key is generated by
 * scripts/gen-app-key.mjs and is safe to commit.
 *
 * This is a SEPARATE key from the catalog pack key (server/lib/catalogPack/
 * trustedKey.ts) so the two release channels have independent blast radius.
 *
 * To rotate the key: re-run scripts/gen-app-key.mjs and ship a new binary.
 */
export const APP_UPDATE_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAC5Wc+EatvH7Uvxu+COQrONmPd62M9vwkF9Ck/aeJwAs=
-----END PUBLIC KEY-----`;
