/**
 * Ed25519 public key used to verify catalog pack manifests.
 *
 * The matching private key lives in the CATALOG_PACK_SIGNING_KEY CI secret
 * (base64-encoded PKCS8 PEM). This public key was generated by
 * scripts/gen-pack-key.mjs and is safe to commit.
 *
 * To rotate the key: re-run scripts/gen-pack-key.mjs.
 */
export const TRUSTED_PUBLIC_KEY_PEM = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEALx3YO/kHCuqROsdugVQAEG9PhZ/iKWzIvQnRDtgZKoQ=
-----END PUBLIC KEY-----`;
