import type { CatalogEntry } from '../lib/types/catalog.js';
export type { CatalogEntry };
import { SOLAR_SYSTEM_MAP } from './solar-system-catalog.js';

// ─── Curated catalog (with descriptions) ────────────────────────────
// Generated by scripts/build-catalog-curated.mjs — re-run to refresh.
import curatedJson from './catalog-curated.json';

const catalog: CatalogEntry[] = curatedJson as CatalogEntry[];
const curatedMap = new Map(catalog.map(e => [e.id.toUpperCase(), e]));

// ─── OpenNGC: comprehensive catalog of 12,000+ NGC/IC/Messier objects ──
// Source: https://github.com/mattiaverga/OpenNGC (CC BY-SA 4.0)
// Imported once as static JSON — no API calls needed.

// Inlined at bundle time by tsup/esbuild — no runtime file access needed.
import openNgcJson from './openngc.json';
import { caldwellToNgcId } from '../lib/caldwellCatalog.js';
import { mergeOverride, entryFromOverride } from '../lib/catalogOverrides.js';
import { getSharplessEntry, sharplessToCatalogEntry } from '../lib/sharplessCatalog.js';

interface OpenNGCEntry {
  id: string;
  type: string;
  constellation: string | null;
  messier?: number | string | null;
  magnitude?: number | null;
  name?: string;
  ra?: number | string | null;
  dec?: number | string | null;
  ngcName?: string;
  typeCode?: string;
  majorAxisArcmin?: number | null;
  commonNames?: string[];
}

/**
 * Runtime validator for OpenNGC entries — matches the minimum shape this
 * module reads out of the bundled JSON. Loose on optional fields (the
 * catalog file has many nullable/missing fields), strict on the required
 * `id` and `type` that every lookup depends on.
 */
function isOpenNGCEntry(value: unknown): value is OpenNGCEntry {
  if (value === null || typeof value !== 'object') return false;
  const v = value as Record<string, unknown>;
  return typeof v.id === 'string' && typeof v.type === 'string';
}

function parseOpenNgcJson(data: unknown): OpenNGCEntry[] {
  if (!Array.isArray(data)) {
    throw new Error('[catalog] openngc.json: expected top-level array');
  }
  // Spot-check the first row so a malformed bundle surfaces at boot, not on
  // the first lookup. The file is generated by a repo-local script, so any
  // shape drift is a build-time bug.
  if (data.length > 0 && !isOpenNGCEntry(data[0])) {
    throw new Error('[catalog] openngc.json: entry missing required id/type strings');
  }
  // Trust boundary — shape validated by isOpenNGCEntry above.
  return data as OpenNGCEntry[];
}

const openNgcData: OpenNGCEntry[] = parseOpenNgcJson(openNgcJson);

// Build lookup maps: by ID, by Messier designation
const openNgcMap = new Map<string, OpenNGCEntry>();
const messierToNgc = new Map<string, OpenNGCEntry>();

for (const entry of openNgcData) {
  openNgcMap.set(entry.id.toUpperCase(), entry);
  if (entry.messier != null) {
    messierToNgc.set(`M${entry.messier}`.toUpperCase(), entry);
  }
}

console.log(`[catalog] Loaded ${openNgcData.length} OpenNGC entries, ${messierToNgc.size} Messier cross-references`);

/**
 * Static-data lookup chain for a catalog entry. Internal helper — public
 * callers should use getCatalogEntry, which wraps this with user overrides.
 *
 * Recursing into this function (not into getCatalogEntry) for the Caldwell
 * alias step keeps override application a single, top-level concern: the
 * override for the requested id is the only one that ever applies, even if
 * an override also happens to exist for the underlying NGC backing the alias.
 */
function lookupCatalogEntry(id: string): CatalogEntry | undefined {
  const key = id.toUpperCase().replace(/\s+/g, '');

  // 0. Solar system objects (Moon, planets, named moons, etc.)
  const solarEntry = SOLAR_SYSTEM_MAP.get(key);
  if (solarEntry) return solarEntry;

  // 1. Curated entry (has description, hand-picked data)
  const curated = curatedMap.get(key);
  if (curated) return curated;

  // 1b. Caldwell C-number (e.g. "C21") → resolve to NGC/IC id first
  const ngcAlias = caldwellToNgcId(key);
  if (ngcAlias) {
    const aliasKey = ngcAlias.toUpperCase().replace(/\s+/g, '');
    const aliasEntry = lookupCatalogEntry(aliasKey);
    if (aliasEntry) {
      // Return the entry with the Caldwell id so callers get back "C21" not "NGC4449"
      return { ...aliasEntry, id };
    }
    return undefined;
  }

  // 2. OpenNGC lookup by direct ID (NGC1234, IC567)
  let ngc = openNgcMap.get(key);

  // 2b. Zero-pad NGC/IC numbers to 4 digits (NGC925 -> NGC0925)
  if (!ngc) {
    const padMatch = key.match(/^(NGC|IC)(\d{1,3})$/);
    if (padMatch) {
      const padded = `${padMatch[1]}${padMatch[2].padStart(4, '0')}`;
      ngc = openNgcMap.get(padded);
    }
  }

  // 3. Messier lookup (M31 -> NGC224)
  if (!ngc && key.startsWith('M')) {
    ngc = messierToNgc.get(key);
  }

  if (ngc) {
    return {
      id: ngc.messier != null ? `M ${ngc.messier}` : ngc.id,
      name: ngc.name ?? (ngc.messier != null ? `M ${ngc.messier}` : ngc.id),
      type: ngc.type,
      constellation: ngc.constellation ?? '',
      magnitude: ngc.magnitude ?? undefined,
      description: '',
      ra: ngc.ra != null ? String(ngc.ra) : undefined,
      dec: ngc.dec != null ? String(ngc.dec) : undefined,
    };
  }

  // 4. Sharpless catalog (Sh2-N emission nebulae)
  const sharpless = getSharplessEntry(key);
  if (sharpless) return sharplessToCatalogEntry(sharpless, id);

  return undefined;
}

/**
 * Get a catalog entry by ID. Checks curated entries first (which have
 * descriptions), then falls back to the comprehensive OpenNGC database.
 *
 * User overrides (catalogOverrides table) are layered on top: any non-null
 * override field wins over the static source. If no static entry exists but
 * an override row does, a synthetic entry is returned — this is how users
 * add objects the bundled catalogs don't know about.
 */
export function getCatalogEntry(id: string): CatalogEntry | undefined {
  const base = lookupCatalogEntry(id);
  if (base) return mergeOverride(base, id);
  return entryFromOverride(id);
}

export function searchCatalog(query: string): CatalogEntry[] {
  const q = query.toLowerCase();
  // Search curated first, then OpenNGC
  const results: CatalogEntry[] = catalog.filter(
    e =>
      e.id.toLowerCase().includes(q) ||
      e.name.toLowerCase().includes(q) ||
      e.constellation.toLowerCase().includes(q) ||
      e.type.toLowerCase().includes(q)
  );

  // Add OpenNGC matches not already in curated results
  const seen = new Set(results.map(r => r.id.toUpperCase()));
  for (const ngc of openNgcData) {
    const messierStr = ngc.messier != null ? String(ngc.messier) : null;
    const matchId = (messierStr ?? ngc.id).toUpperCase();
    if (seen.has(matchId)) continue;
    if (
      ngc.id.toLowerCase().includes(q) ||
      (messierStr && messierStr.toLowerCase().includes(q)) ||
      (ngc.name && ngc.name.toLowerCase().includes(q)) ||
      (ngc.constellation && ngc.constellation.toLowerCase().includes(q)) ||
      ngc.type.toLowerCase().includes(q)
    ) {
      results.push({
        id: messierStr ?? ngc.id,
        name: ngc.name ?? messierStr ?? ngc.id,
        type: ngc.type,
        constellation: ngc.constellation ?? '',
        magnitude: ngc.magnitude ?? undefined,
        description: '',
        ra: ngc.ra != null ? String(ngc.ra) : undefined,
        dec: ngc.dec != null ? String(ngc.dec) : undefined,
      });
      seen.add(matchId);
    }
  }

  return results;
}

export function getAllCatalogEntries(): CatalogEntry[] {
  return catalog;
}
